# Generated by Django 4.1.1 on 2022-10-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='static/images/logo')),
                ('heading_title', models.CharField(max_length=50, null=True)),
                ('heading_description', models.CharField(max_length=300, null=True)),
                ('company_img1', models.ImageField(blank=True, null=True, upload_to='static/images/google')),
                ('company_img2', models.ImageField(blank=True, null=True, upload_to='static/images/microsoft')),
                ('mid_img', models.ImageField(blank=True, null=True, upload_to='static/images/job')),
                ('mid_title', models.CharField(max_length=50, null=True)),
                ('mid_description', models.CharField(max_length=300, null=True)),
                ('scroll_title', models.CharField(max_length=50, null=True)),
                ('end_title', models.CharField(max_length=50, null=True)),
                ('about_us', models.CharField(max_length=50, null=True)),
                ('end_description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='latestblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog1', models.CharField(max_length=50, null=True)),
                ('blog1descript', models.CharField(max_length=300, null=True)),
                ('blog2', models.CharField(max_length=50, null=True)),
                ('blog2descript', models.CharField(max_length=300, null=True)),
                ('blog3', models.CharField(max_length=50, null=True)),
                ('blog3descript', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images1', models.FileField(upload_to='multipleimages1/')),
                ('images2', models.FileField(upload_to='multipleimages2/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.index')),
            ],
        ),
    ]
