# Generated by Django 4.1.1 on 2022-10-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_title', models.CharField(max_length=50, null=True)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='static/images/banner')),
                ('mid_title', models.CharField(max_length=50, null=True)),
                ('mid_description', models.CharField(max_length=300, null=True)),
                ('overviewtitle', models.CharField(max_length=50, null=True)),
                ('overviewdescription', models.CharField(max_length=300, null=True)),
                ('end_title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_title', models.CharField(max_length=50, null=True)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='static/images/banner')),
                ('mid_title', models.CharField(max_length=50, null=True)),
                ('blog1descript', models.CharField(max_length=300, null=True)),
                ('blog2descript', models.CharField(max_length=300, null=True)),
                ('blog3descript', models.CharField(max_length=300, null=True)),
                ('blog4descript', models.CharField(max_length=300, null=True)),
                ('blog5descript', models.CharField(max_length=300, null=True)),
                ('blog6descript', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_title', models.CharField(max_length=50, null=True)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='static/images/banner')),
                ('mid_title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(blank=True, choices=[('5', '5'), ('1', '1'), ('3', '3'), ('4', '4'), ('2', '2')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_title', models.CharField(max_length=50, null=True)),
                ('mid_title', models.CharField(max_length=50, null=True)),
                ('categories', models.CharField(max_length=50, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.id')),
            ],
        ),
        migrations.CreateModel(
            name='Aboutusimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images1', models.FileField(upload_to='multipleimages1/')),
                ('images2', models.FileField(upload_to='multipleimages2/')),
                ('about', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.aboutus')),
            ],
        ),
    ]
