# Generated by Django 4.1.1 on 2022-10-07 09:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_background_alter_aboutus_mid_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='footer_description',
            field=tinymce.models.HTMLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='footer_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('1', '1'), ('5', '5'), ('3', '3')], max_length=1, null=True),
        ),
    ]
