# Generated by Django 4.1.1 on 2022-10-07 09:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_index_footer_description_alter_id_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='footer_description',
            field=tinymce.models.HTMLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('2', '2'), ('4', '4'), ('1', '1')], max_length=1, null=True),
        ),
    ]
