# Generated by Django 4.1.1 on 2022-10-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_index_footer_description_alter_id_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='footer_description',
            new_name='aboutus_description',
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('2', '2'), ('1', '1'), ('5', '5')], max_length=1, null=True),
        ),
    ]
