# Generated by Django 4.1.1 on 2022-10-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_rename_footer_description_index_aboutus_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='about_us',
            new_name='about_us1',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='end_title',
            new_name='about_us2',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='footer_title',
            new_name='end_title1',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='heading_title',
            new_name='end_title2',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='mid_title',
            new_name='footer_title1',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='scroll_title',
            new_name='footer_title2',
        ),
        migrations.AddField(
            model_name='index',
            name='heading_title1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='heading_title2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='mid_title1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='mid_title2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='scroll_title1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='scroll_title2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2'), ('5', '5')], max_length=1, null=True),
        ),
    ]
