# Generated by Django 4.1.1 on 2022-10-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_aboutus_mid_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2'), ('5', '5')], max_length=1, null=True),
        ),
    ]
