# Generated by Django 4.1.1 on 2022-10-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_id_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='heading_title',
            new_name='heading_title1',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='mid_title',
            new_name='heading_title2',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='overviewtitle',
            new_name='mid_title1',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mid_title2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='overviewtitle1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='overviewtitle2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('5', '5'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
    ]
