# Generated by Django 4.1.1 on 2022-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_rename_heading_title_aboutus_heading_title1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='overviewdescription',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='overviewtitle1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='overviewtitle2',
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('5', '5'), ('1', '1'), ('3', '3'), ('4', '4'), ('2', '2')], max_length=1, null=True),
        ),
    ]
