# Generated by Django 4.1.1 on 2022-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_rename_heading_title_contact_heading_title1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mid_title',
            new_name='mid_title1',
        ),
        migrations.AddField(
            model_name='contact',
            name='mid_title2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('4', '4'), ('1', '1'), ('2', '2'), ('3', '3'), ('5', '5')], max_length=1, null=True),
        ),
    ]
