# Generated by Django 4.1.1 on 2022-10-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_rename_mid_title_contact_mid_title1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_title1', models.CharField(max_length=50, null=True)),
                ('heading_title2', models.CharField(max_length=50, null=True)),
                ('mid_title1', models.CharField(max_length=50, null=True)),
                ('mid_title2', models.CharField(max_length=50, null=True)),
                ('end_title1', models.CharField(max_length=50, null=True)),
                ('end_title2', models.CharField(max_length=50, null=True)),
                ('footer_title1', models.CharField(max_length=50, null=True)),
                ('footer_title2', models.CharField(max_length=50, null=True)),
                ('categories', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog4descript',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog5descript',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog6descript',
        ),
        migrations.AlterField(
            model_name='id',
            name='classes',
            field=models.CharField(blank=True, choices=[('5', '5'), ('3', '3'), ('4', '4'), ('2', '2'), ('1', '1')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.id'),
        ),
    ]
