# Generated by Django 4.1.1 on 2022-10-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200, null=True)),
                ('employer', models.CharField(max_length=100)),
                ('number_of_employee', models.IntegerField(null=True)),
                ('established_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('about_company', models.TextField(max_length=2000)),
                ('Facebook', models.URLField(blank=True)),
                ('Twitter', models.URLField(blank=True)),
                ('Linkedin', models.URLField(blank=True)),
                ('Instagram', models.URLField(blank=True)),
                ('Youtube', models.URLField(blank=True)),
                ('Others', models.URLField(blank=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='companyimage')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('job_seeker_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('otp', models.CharField(blank=True, max_length=7, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('looking_for', models.CharField(default='Full Time', max_length=30, null=True)),
                ('workig_experiance', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('about_me', models.CharField(blank=True, max_length=2000, null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profileimage')),
                ('my_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
